In [7]:
#Q1:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
add_result = arr + 2
mul_result = arr * 3
div_result = arr / 2
print("Addition:", add_result)
print("Multiplication:", mul_result)
print("Division:", div_result)

Addition: [3 4 5 6 7]
Multiplication: [ 3  6  9 12 15]
Division: [0.5 1.  1.5 2.  2.5]


In [8]:
#Q2:
import numpy as np
numbers = np.array([1, 2, 3, 6, 4, 5])
reversed_numbers = numbers[::-1]
print("Reversed Array:", reversed_numbers)
array1 = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1])
array2 = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
most_common1 = np.bincount(array1).argmax()
most_common2 = np.bincount(array2).argmax()
indices1 = np.where(array1 == most_common1)[0]
indices2 = np.where(array2 == most_common2)[0]
print("Most frequent in array1:", most_common1, "at positions", indices1)
print("Most frequent in array2:", most_common2, "at positions", indices2)

Reversed Array: [5 4 6 3 2 1]
Most frequent in array1: 1 at positions [0 5 7 8]
Most frequent in array2: 1 at positions [0 1 2]


In [9]:
#Q3:
arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
print("Element at 1st row, 2nd column:", arr[0, 1])
print("Element at 3rd row, 1st column:", arr[2, 0])

Element at 1st row, 2nd column: 20
Element at 3rd row, 1st column: 70


In [10]:
#Q4:
name = "Sameer"
arr = np.linspace(10, 100, 25)
print(f"Array: {arr}")
print("Dimensions:", arr.ndim)
print("Shape:", arr.shape)
print("Data Type:", arr.dtype)
print("Total Bytes:", arr.nbytes)
reshaped_arr = arr.reshape(5, 5)
transposed_arr = reshaped_arr.T
print("Transposed Array:\n", transposed_arr)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Data Type: float64
Total Bytes: 200
Transposed Array:
 [[ 10.    28.75  47.5   66.25  85.  ]
 [ 13.75  32.5   51.25  70.    88.75]
 [ 17.5   36.25  55.    73.75  92.5 ]
 [ 21.25  40.    58.75  77.5   96.25]
 [ 25.    43.75  62.5   81.25 100.  ]]


In [11]:
#Q5:
name = "Sameer"

ucs420_arr = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 15, 20, 35]
])

print("Mean:", np.mean(ucs420_arr))
print("Median:", np.median(ucs420_arr))
print("Max:", np.max(ucs420_arr))
print("Min:", np.min(ucs420_arr))
print("Unique Elements:", np.unique(ucs420_arr))

reshaped_arr = ucs420_arr.reshape(4, 3)
print("Reshaped (4x3):\n", reshaped_arr)

resized_arr = ucs420_arr.reshape(2, 6)
print("Resized (2x6):\n", resized_arr)

Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized (2x6):
 [[10 20 30 40 50 60]
 [70 80 90 15 20 35]]
